# Generated by Django 5.1 on 2024-09-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_data',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_total', models.IntegerField(null=True)),
                ('order_date', models.DateField(null=True)),
                ('order_address', models.CharField(max_length=200, null=True)),
                ('order_tel', models.CharField(max_length=11, null=True)),
                ('order_username', models.CharField(max_length=100, null=True)),
                ('order_email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product_data',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_qty', models.IntegerField(null=True)),
                ('product_price', models.IntegerField(null=True)),
                ('product_detail', models.TextField(null=True)),
                ('product_image1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_qty', models.IntegerField(null=True)),
                ('prod_price', models.IntegerField(null=True)),
                ('order_id_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atbadminton.order_data')),
                ('prod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atbadminton.product_data')),
            ],
        ),
        migrations.CreateModel(
            name='cart_add',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_qty', models.IntegerField(null=True)),
                ('product_price', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atbadminton.product_data')),
            ],
        ),
    ]
